### PR TITLE
Fix target property of topic update message

### PR DESCRIPTION
**Pull request by galfert**
Was the same as the actor (ie. the person), but should be the channel instead.

### CODE REVIEW

**Comment by skddc** [comment]
Should probably be tested in https://github.com/sockethub/sockethub-platform-irc/blob/master/test/24-irc-suite.js

**Comment by galfert** [comment]
I couldn't get the tests to run.

Failed with `TypeError: Cannot read property 'enum' of undefined`.

**Comment by galfert** [comment]
Was able to fix most of the tests. They were broken mostly due to the recently renamed properties. There is one failing test left that I couldn't figure out yet.

I also couldn't find out how to write a test for my fix. The test suite only seems to test the core functions that **send out** messages to IRC, but not the listener that builds the objects from the messages that are **coming in** from IRC.

@silverbucket any hints how to test this would be greatly appreciated :)

**Comment by skddc** [comment]
@silverbucket Would be great if you could help @galfert to finish this soon. We have to branch off of this one for another fix now, so we don't lose the fixes for Hyperchannel.

**Comment by silverbucket** [comment]
@galfert thanks for this patch! it looks good.

as for testing incoming data - yeah, this is something I have been meaning to think of a way to do but haven't come up with any good ideas yet (I haven't had any time to really look at it, but it's something I know we should have). Do you have any ideas as to a good way to do it?

One thing we could do is instantiate the platform, with a dummy/mock session object, then send in some JSON(*), and the dummy/mock callback can test the resulting data.

* The problem is we're currently interfacing directly with the IRC library. We need some way to abstract that stuff so it's easy to inject dummy data without having to mock the entire IRC library. I've read some ideas for doing this with dependency injection but don't feel like I understand it enough to go ahead and start doing it. Any help or discussion about this would be welcome.

**Comment by skddc** [comment]
It sounds like that's getting mighty complicated, and dependent on mocks that differ from the real world then. Have you thought about a proper setup with an actual IRC server and connection in the mix? For example using Vagrant with a provisionier, or Docker or a mix of those...

**Pull request merged**
